app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */
Route::get('/', function () {
    return redirect('/admin/blended');
});
//Route::get('session', function () {
//    dd(session()->all());
//});
Route::group(['prefix' => 'exp'], function () {
    Route::get('validation', 'ExperimentsController@create')->name('exp.validation.create');
    Route::get('validation/edit', 'ExperimentsController@edit')->name('exp.validation.edit');
    Route::post('validation', 'ExperimentsController@store')->name('exp.validation.store');
    Route::patch('validation/update', 'ExperimentsController@update')->name('exp.validation.update');
    Route::get('ajax', 'ExperimentsController@ajax')->name('exp.ajax');
    Route::get('auth', ['uses' => 'ExperimentsController@auth', 'middleware' => 'auth']);
    Route::get('instance', 'ExperimentsController@instanceTrial');
    Route::post('request', 'ExperimentsController@req');
    Route::get('chkbox', function () {
        return view('experiments.checkboxes');
    });
});
//$modules = modules();
//foreach ($modules as $module) {
//    Route::group(['middleware' => ['auth', 'admin', 'module'], 'prefix' => "admin/{$module}", 'as' => "admin.{$module}."], function () use ($module) {
//        foreach (module($module)->getActionsList() as $action) {
//            custom_action($action);
//        }
//    });
//}
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin/shift', 'as' => 'admin.shift.'], function () {
    Route::get('/', 'ShiftController@index')->name('index');
    Route::get('{id}/edit', 'ShiftController@edit')->name('edit');
    Route::delete('{id}/delete', 'ShiftController@delete')->name('delete');
    Route::get('create', 'ShiftController@create')->name('create');
    Route::delete('delete_multiple', 'ShiftController@deleteMultiple')->name('delete_multiple');
    Route::post('store', 'ShiftController@store')->name('store');
    Route::patch('{id}/update', 'ShiftController@update')->name('update');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin/backend_user', 'as' => 'admin.backend_user.'], function () {
    Route::get('/', 'BackendUserController@index')->name('index');
    Route::get('create', 'BackendUserController@create')->name('create');
    Route::get('{id}/edit', 'BackendUserController@edit')->name('edit');
    Route::post('store', 'BackendUserController@store')->name('store');
    Route::patch('{id}/update', 'BackendUserController@update')->name('update');
    Route::delete('{id}/delete', 'BackendUserController@delete')->name('delete');
    Route::delete('delete_multiple', 'BackendUserController@deleteMultiple')->name('delete_multiple');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin/faq_category', 'as' => 'admin.faq_category.'], function() {
    Route::get('/', 'FaqCategoryController@index')->name('index');
    Route::get('create', 'FaqCategoryController@create')->name('create');
    Route::get('{id}/edit', 'FaqCategoryController@edit')->name('edit');
    Route::post('reorder', 'FaqCategoryController@reorder')->name('reorder');
    Route::post('store', 'FaqCategoryController@store')->name('store');
    Route::patch('{id}/update', 'FaqCategoryController@update')->name('update');
    Route::delete('{id}/delete', 'FaqCategoryController@delete')->name('delete');
    Route::delete('delete_multiple', 'FaqCategoryController@deleteMultiple')->name('delete_multiple');
});
Route::group(['middleware' => ['auth', 'faqs'], 'prefix' => "admin/faq", 'as' => "admin.faq."], function () {
    Route::get('create', 'FaqController@create')->name('create');
    Route::get('{status}', 'FaqController@index')->name('index');
    Route::get('{id}/edit', 'FaqController@edit')->name('edit');
    Route::get('{id}/review_pending', 'FaqController@reviewPending')->name('review_pending');
    Route::delete('{id}/delete', 'FaqController@delete')->name('delete');
    Route::delete('delete_multiple', 'FaqController@deleteMultiple')->name('delete_multiple');
    Route::post('{id}/reorder', 'FaqController@reorder')->name('reorder');
    Route::post('store', 'FaqController@store')->name('store');
    Route::patch('{id}/update', 'FaqController@update')->name('update');
    Route::post('publish_new', 'FaqController@publishNew')->name('publish_new');
    Route::patch('{id}/publish', 'FaqController@publish')->name('publish');
    Route::get('{id}/modify', 'FaqController@getModify')->name('get_modify');
    Route::get('{id}/review_modification', 'FaqController@reviewModification')->name('review_modification');
    Route::patch('{id}/modify', 'FaqController@modify')->name('modify');
    Route::delete('{id}/reject', 'FaqController@reject')->name('reject');
    Route::patch('{id}/confirm', 'FaqController@confirm')->name('confirm');
    Route::patch('{id}/confirm_modification', 'FaqController@confirmModification')->name('confirm_modification');
    Route::delete('{id}/reject_modification', 'FaqController@rejectModification')->name('reject_modification');
});
Route::group(['middleware' => ['auth', 'faqs'], 'prefix' => "admin/user_question", 'as' => "admin.user_question."], function () {
    Route::get('{status}', 'UserQuestionController@index')->name('index');
    Route::get('{id}/answer', 'UserQuestionController@answer')->name('answer');
    Route::get('{id}/view', 'UserQuestionController@view')->name('view');
    Route::patch('{id}/send', 'UserQuestionController@send')->name('send');
    Route::post('{id}/copy', 'UserQuestionController@copy')->name('copy');
    Route::patch('{id}/report', 'UserQuestionController@report')->name('report');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/one_on_one", 'as' => "admin.one_on_one."], function () {
    Route::get('/', 'OneOnOneController@index')->name('index');
    Route::post('init', 'OneOnOneController@init')->name('init');
    Route::post('{id}/init_level', 'OneOnOneController@initLevel')->name('init_level');
    Route::delete('{id}/delete', 'OneOnOneController@delete')->name('delete');
    Route::delete('{id}/delete_level', 'OneOnOneController@deleteLevel')->name('delete_level');
    Route::post('{id}/init_objective', 'OneOnOneController@initObjective')->name('init_objective');
    Route::delete('delete_objective', 'OneOnOneController@deleteObjective')->name('delete_objective');
    Route::post('{id}/init_pricing', 'OneOnOneController@initPricing')->name('init_pricing');
    Route::delete('{id}delete_pricing', 'OneOnOneController@deletePricing')->name('delete_pricing');
    Route::patch('{id}/update', 'OneOnOneController@store')->name('update');
    Route::patch('{id}/publish', 'OneOnOneController@publish')->name('publish');
    Route::post('{id}/upload_ig', 'OneOnOneController@uploadIg')->name('upload_ig');
    Route::get('level/{id}/ig', 'OneOnOneController@ig')->name('ig');
    Route::delete('level/{id}/delete_ig', 'OneOnOneController@deleteIg')->name('delete_ig');
    Route::post('{id}/upload_material', 'OneOnOneController@uploadMaterial')->name('upload_material');
    Route::get('level/{id}/material', 'OneOnOneController@material')->name('material');
    Route::delete('level/{id}/delete_material', 'OneOnOneController@deleteMaterial')->name('delete_material');
    Route::post('{id}/upload_section_image', 'OneOnOneController@uploadSectionImage')->name('upload_section_image');
    Route::get('level/{id}/section_image', 'OneOnOneController@sectionImage')->name('section_image');
    Route::delete('level/{id}/delete_section_image', 'OneOnOneController@deleteSectionImage')->name('delete_section_image');
    Route::post('{id}upload_course_image', 'OneOnOneController@uploadCourseImage')->name('upload_course_image');
    Route::get('level/{id}/course_image', 'OneOnOneController@courseImage')->name('course_image');
    Route::delete('level/{id}/delete_course_image', 'OneOnOneController@deleteCourseImage')->name('delete_course_image');
    Route::post('{id}/upload_promo', 'OneOnOneController@uploadPromo')->name('upload_promo');
    Route::get('level/{id}/promo', 'OneOnOneController@promo')->name('promo');
    Route::delete('level/{id}/delete_promo', 'OneOnOneController@deletePromo')->name('delete_promo');
    Route::get('{id}/edit', 'OneOnOneController@edit')->name('edit');
    Route::patch('{id}/update', 'OneOnOneController@update')->name('update');
    Route::patch('{id}/publish', 'OneOnOneController@publish')->name('publish');
});

Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/blended", 'as' => "admin.blended."], function () {
    Route::get('/', 'BlendedController@index')->name('index');
    Route::post('init', 'BlendedController@init')->name('init');
    Route::get('{id}/edit', 'BlendedController@edit')->name('edit');
    Route::delete('{id}/delete', 'BlendedController@delete')->name('delete');
    Route::post('{id}/upload_section_image', 'BlendedController@uploadSectionImage')->name('upload_section_image');
    Route::post('{id}/upload_course_image', 'BlendedController@uploadCourseImage')->name('upload_course_image');
    Route::post('{id}/upload_course_material', 'BlendedController@uploadCourseMaterial')->name('upload_course_material');
    Route::post('{id}/upload_promo', 'BlendedController@uploadPromo')->name('upload_promo');
    Route::get('{id}/section_image', 'BlendedController@sectionImage')->name('section_image');
    Route::get('{id}/course_image', 'BlendedController@courseImage')->name('course_image');
    Route::get('{id}/course_material', 'BlendedController@courseMaterial')->name('course_material');
    Route::get('{id}/promo', 'BlendedController@promo')->name('promo');

app/FaqCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FaqCategory extends Model {

    use Traits\TrimScalarValues;

    protected $fillable = ['name'];

    public static function boot() {
        parent::boot();
        static::deleting(function ($category) {
            $category->faqs()->update(['category_id' => null]);
        });
        static::creating(function ($faqCategory) {
            $faqCategory->stuff_order = static::query()->max('stuff_order') + 1;
        });
    }

    public function faqs() {
        return $this->hasMany('App\Faq', 'category_id');
    }

}

app/Http/Controllers/FaqCategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\FaqCategory;
use Validator;

class FaqCategoryController extends Controller {

    public function index() {
        $categories = FaqCategory::orderBy('stuff_order')->get();
        $data = [];
        $data['categories'] = $categories;
        $data['partialView'] = 'faq_category.list';
        return view('faq_category.base', $data);
    }

    public function create() {
        $data = [];
        $data['category'] = false;
        $data['partialView'] = 'faq_category.form';
        return view('faq_category.base', $data);
    }

    public function edit($id) {
        $category = FaqCategory::findOrFail($id);
        $data = [];
        $data['category'] = $category;
        $data['partialView'] = 'faq_category.form';
        return view('faq_category.base', $data);
    }

    public function store(Request $request) {
        $rules = ['name' => 'required|unique:faq_categories,name'];
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->messages()]);
        }
        $category = new FaqCategory();
        $category->name = $request->name;
        $category->save();
        return response()->json(['url' => route('admin.faq_category.index')]);
    }

    public function update($id, Request $request) {
        $category = FaqCategory::findOrFail($id);
        $rules = ['name' => 'required|unique:faq_categories,name,' . $id];
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()->messages()]);
        }
        $category->name = $request->name;
        $category->save();

        return response()->json(['url' => route('admin.faq_category.index')]);
    }

    public function delete($id) {
        FaqCategory::destroy($id);
    }

    public function deleteMultiple(Request $request) {
        FaqCategory::destroy($request->items);
    }

    public function reorder(Request $request) {
        $newSequence = $request->orderList;
        if (!is_array($newSequence)) {
            abort(400);
        }
        $allCount = FaqCategory::count();
        $foundCount = FaqCategory::whereIn('id', $newSequence)->count();
        $newSequenceCount = count($newSequence);
        if ($newSequenceCount != $allCount || $newSequenceCount != $foundCount) {
            abort(400);
        }
        $order = 1;
        foreach ($newSequence as $id) {
            FaqCategory::where('id', '=', $id)->update(['stuff_order' => $order++]);
        }
    }

}

resources/views/faq_category/base.blade.php
<?php
$i = 'faqs';
$j = 'categories';
?>

@extends('admin.master')
@section('plugins_css')
<link href="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/sweetAlert/sweetalert.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/dragula/dragula.min.css')}}"/>
@endSection

@section('plugins_js')
<script type="text/javascript" src="{{asset('assets/global/scripts/datatable.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/datatables.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/plugins/dataTables.rowReorder.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/jsvalidation.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/sweetAlert/sweetalert.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/dragula/dragula.min.js')}}"></script>
@endSection

@section('page_js')
<script type="text/javascript" src="{{asset('assets/admin/pages/scripts/faq_category.js')}}"></script>
@endSection

@section('add_inits')

@stop

@section('title')
FAQ Categories
@stop

@section('page_title')
FAQ Categories
@stop

@section('page_title_small')

@stop

@section('content')
@include($partialView)
@stop

resources/views/faq_category/form.blade.php
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>FAQ Category</div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <div class="form form-horizontal" id="main-form" role="form">
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Name</label>
                    <div class="col-md-4">
                        <input name="name" type="text" value="{{$category->name or ''}}" class="form-control">
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="btn-set pull-right">
                    <button type="submit" class="btn btn-lg green" id="save"
                            @if($category)
                            data-action="{{route('admin.faq_category.update',['id'=>$category->id])}}"
                            data-method="patch"
                            @else
                            data-action="{{route('admin.faq_category.store')}}"
                            data-method="post"
                            @endif
                            >Save</button>
                </div>
            </div>
        </div>
        <!-- END FORM-->
    </div>
</div>

resources/views/faq_category/list.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>FAQ Categories
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                        <a href="{{route('admin.faq_category.create')}}" id="sample_editable_1_new" class="btn green pjax-link">
                            Add New <i class="fa fa-plus"></i>
                        </a>
                        <button disabled class="btn yellow reorder" data-action="{{route('admin.faq_category.reorder')}}">Re-order</button>
                        <button data-form="delete_mul_1" type="button" class="btn red delete_multiple" disabled="disabled" data-model="shift" ><i class="fa fa-remove"></i> Delete</button>
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
        <form id="delete_mul_1" method="post" action="{{route('admin.faq_category.delete_multiple')}}">
            {!! method_field('delete') !!}
            {!! csrf_field() !!}
            <table class="table table-striped table-bordered table-hover table-dt" id="table-dt">
                <thead>
                    <tr class="tr-head">
                        <th valign="middle" class="no-sorting table-checkbox-col">
                            <input type="checkbox" class="group-checkable">
                        </th>
                        <th valign="middle">
                            Name
                        </th>
                        <th class="no-sorting">
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($categories as $category)
                    <tr class="odd gradeX" id="data-row-{{$category->id}}">
                        <td valign="middle">
                            <input type="hidden" value="{{$category->id}}" class="reorder-vals">
                            <input type="checkbox" name="items[]"  class="table-checkbox"  value="{{$category->id}}" >
                        </td>
                        <td valign="middle">
                            {{$category->name}}
                        </td>
                        <td valign="middle">
                            <a href="{{route('admin.faq_category.edit',['id'=>$category->id])}}" class="pjax-link"><button type="button" class="btn green"><i class="fa fa-edit"></i> Edit</button></a>
                            <button type="button" data-action="{{route('admin.faq_category.delete',['id'=>$category->id])}}"  class="btn red remove-category"><i class="fa fa-remove"></i> Delete</button>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </form>
    </div>
</div>