app/Http/routes.php
    Route::delete('delete_multiple', 'ShiftController@deleteMultiple')->name('delete_multiple');
    Route::post('store', 'ShiftController@store')->name('store');
    Route::patch('{id}/update', 'ShiftController@update')->name('update');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin/backend_user', 'as' => 'admin.backend_user.'], function () {
    Route::get('/', 'BackendUserController@index')->name('index');
    Route::get('create', 'BackendUserController@create')->name('create');
    Route::get('{id}/edit', 'BackendUserController@edit')->name('edit');
    Route::post('store', 'BackendUserController@store')->name('store');
    Route::patch('{id}/update', 'BackendUserController@update')->name('update');
    Route::delete('{id}/delete', 'BackendUserController@delete')->name('delete');
    Route::delete('delete_multiple', 'BackendUserController@deleteMultiple')->name('delete_multiple');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin/faq_category', 'as' => 'admin.faq_category.'], function() {
    Route::get('/', 'FaqCategoryController@index')->name('index');
    Route::get('create', 'FaqCategoryController@create')->name('create');
    Route::get('{id}/edit', 'FaqCategoryController@edit')->name('edit');
    Route::post('reorder', 'FaqCategoryController@reorder')->name('reorder');
    Route::post('store', 'FaqCategoryController@store')->name('store');
    Route::patch('{id}/update', 'FaqCategoryController@update')->name('update');
    Route::delete('{id}/delete', 'FaqCategoryController@delete')->name('delete');
    Route::delete('delete_multiple', 'FaqCategoryController@deleteMultiple')->name('delete_multiple');
});
Route::group(['middleware' => ['auth', 'faqs'], 'prefix' => "admin/faq", 'as' => "admin.faq."], function () {
    Route::get('create', 'FaqController@create')->name('create');
    Route::get('{status}', 'FaqController@index')->name('index');
    Route::get('{id}/edit', 'FaqController@edit')->name('edit');
    Route::get('{id}/review_pending', 'FaqController@reviewPending')->name('review_pending');
    Route::delete('{id}/delete', 'FaqController@delete')->name('delete');
    Route::delete('delete_multiple', 'FaqController@deleteMultiple')->name('delete_multiple');
    Route::post('{id}/reorder', 'FaqController@reorder')->name('reorder');
    Route::post('store', 'FaqController@store')->name('store');
    Route::patch('{id}/update', 'FaqController@update')->name('update');
    Route::post('publish_new', 'FaqController@publishNew')->name('publish_new');
    Route::patch('{id}/publish', 'FaqController@publish')->name('publish');
    Route::get('{id}/modify', 'FaqController@getModify')->name('get_modify');
    Route::get('{id}/review_modification', 'FaqController@reviewModification')->name('review_modification');
    Route::patch('{id}/modify', 'FaqController@modify')->name('modify');
    Route::delete('{id}/reject', 'FaqController@reject')->name('reject');
    Route::patch('{id}/confirm', 'FaqController@confirm')->name('confirm');
    Route::patch('{id}/confirm_modification', 'FaqController@confirmModification')->name('confirm_modification');
    Route::delete('{id}/reject_modification', 'FaqController@rejectModification')->name('reject_modification');
});
Route::group(['middleware' => ['auth', 'faqs'], 'prefix' => "admin/user_question", 'as' => "admin.user_question."], function () {
    Route::get('{status}', 'UserQuestionController@index')->name('index');
    Route::get('{id}/answer', 'UserQuestionController@answer')->name('answer');
    Route::get('{id}/view', 'UserQuestionController@view')->name('view');
    Route::patch('{id}/send', 'UserQuestionController@send')->name('send');
    Route::post('{id}/copy', 'UserQuestionController@copy')->name('copy');
    Route::patch('{id}/report', 'UserQuestionController@report')->name('report');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/one_on_one", 'as' => "admin.one_on_one."], function () {
    Route::get('/', 'OneOnOneController@index')->name('index');
    Route::post('init', 'OneOnOneController@init')->name('init');
    Route::post('{id}/init_level', 'OneOnOneController@initLevel')->name('init_level');
    Route::delete('{id}/delete', 'OneOnOneController@delete')->name('delete');
    Route::delete('{id}/delete_level', 'OneOnOneController@deleteLevel')->name('delete_level');
    Route::post('{id}/init_objective', 'OneOnOneController@initObjective')->name('init_objective');
    Route::delete('delete_objective', 'OneOnOneController@deleteObjective')->name('delete_objective');
    Route::post('{id}/init_pricing', 'OneOnOneController@initPricing')->name('init_pricing');
    Route::delete('{id}delete_pricing', 'OneOnOneController@deletePricing')->name('delete_pricing');
    Route::patch('{id}/update', 'OneOnOneController@store')->name('update');
    Route::patch('{id}/publish', 'OneOnOneController@publish')->name('publish');
    Route::post('{id}/upload_ig', 'OneOnOneController@uploadIg')->name('upload_ig');
    Route::get('level/{id}/ig', 'OneOnOneController@ig')->name('ig');
    Route::delete('level/{id}/delete_ig', 'OneOnOneController@deleteIg')->name('delete_ig');
    Route::post('{id}/upload_material', 'OneOnOneController@uploadMaterial')->name('upload_material');
    Route::get('level/{id}/material', 'OneOnOneController@material')->name('material');
    Route::delete('level/{id}/delete_material', 'OneOnOneController@deleteMaterial')->name('delete_material');
    Route::post('{id}/upload_section_image', 'OneOnOneController@uploadSectionImage')->name('upload_section_image');
    Route::get('level/{id}/section_image', 'OneOnOneController@sectionImage')->name('section_image');
    Route::delete('level/{id}/delete_section_image', 'OneOnOneController@deleteSectionImage')->name('delete_section_image');
    Route::post('{id}upload_course_image', 'OneOnOneController@uploadCourseImage')->name('upload_course_image');
    Route::get('level/{id}/course_image', 'OneOnOneController@courseImage')->name('course_image');
    Route::delete('level/{id}/delete_course_image', 'OneOnOneController@deleteCourseImage')->name('delete_course_image');
    Route::post('{id}/upload_promo', 'OneOnOneController@uploadPromo')->name('upload_promo');
    Route::get('level/{id}/promo', 'OneOnOneController@promo')->name('promo');
    Route::delete('level/{id}/delete_promo', 'OneOnOneController@deletePromo')->name('delete_promo');
    Route::get('{id}/edit', 'OneOnOneController@edit')->name('edit');
    Route::patch('{id}/update', 'OneOnOneController@update')->name('update');
    Route::patch('{id}/publish', 'OneOnOneController@publish')->name('publish');
});

Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/blended", 'as' => "admin.blended."], function () {
    Route::get('/', 'BlendedController@index')->name('index');
    Route::post('init', 'BlendedController@init')->name('init');
    Route::get('{id}/edit', 'BlendedController@edit')->name('edit');
    Route::delete('{id}/delete', 'BlendedController@delete')->name('delete');
    Route::post('{id}/upload_section_image', 'BlendedController@uploadSectionImage')->name('upload_section_image');
    Route::post('{id}/upload_course_image', 'BlendedController@uploadCourseImage')->name('upload_course_image');
    Route::post('{id}/upload_course_material', 'BlendedController@uploadCourseMaterial')->name('upload_course_material');
    Route::post('{id}/upload_promo', 'BlendedController@uploadPromo')->name('upload_promo');
    Route::get('{id}/section_image', 'BlendedController@sectionImage')->name('section_image');
    Route::get('{id}/course_image', 'BlendedController@courseImage')->name('course_image');
    Route::get('{id}/course_material', 'BlendedController@courseMaterial')->name('course_material');
    Route::get('{id}/promo', 'BlendedController@promo')->name('promo');
    Route::delete('{id}/delete_section_image', 'BlendedController@deleteSectionImage')->name('delete_section_image');
    Route::delete('{id}/delete_course_image', 'BlendedController@deleteCourseImage')->name('delete_course_image');
    Route::delete('{id}/delete_course_material', 'BlendedController@deleteCourseMaterial')->name('delete_course_material');
    Route::delete('{id}/delete_promo', 'BlendedController@deletePromo')->name('delete_promo');
    Route::patch('{id}/update', 'BlendedController@update')->name('update');
    Route::patch('{id}/publish', 'BlendedController@publish')->name('publish');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/blended_template", 'as' => "admin.blended_template."], function () {
    Route::get('/', 'BlendedTemplateController@index')->name('index');
    Route::post('init', 'BlendedTemplateController@init')->name('init');
    Route::get('{id}/edit', 'BlendedTemplateController@edit')->name('edit');
    Route::post('{id}/upload_ig', 'BlendedTemplateController@uploadIg')->name('upload_ig');
    Route::get('{id}/ig', 'BlendedTemplateController@ig')->name('ig');
    Route::delete('{id}/delete_ig', 'BlendedTemplateController@deleteIg')->name('delete_ig');
    Route::patch('{id}/update', 'BlendedTemplateController@update')->name('update');
    Route::patch('{id}/publish', 'BlendedTemplateController@publish')->name('publish');
    Route::post('{id}/init_session', 'BlendedTemplateController@initSession')->name('init_session');
    Route::delete('{id}/delete_session', 'BlendedTemplateController@deleteSession')->name('delete_session');
    Route::post('{id}/upload_session_material', 'BlendedTemplateController@uploadSessionMaterial')->name('upload_session_material');
    Route::get('{id}/session_material', 'BlendedTemplateController@session_material')->name('session_material');
    Route::delete('{id}/delete_session_material', 'BlendedTemplateController@deleteSessionMaterial')->name('delete_session_material');
    Route::post('{id}/upload_session_content', 'BlendedTemplateController@uploadSessionContent')->name('upload_session_content');

app/UserQuestion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserQuestion extends Model {

    use Traits\TrimScalarValues;
}

app/Http/Controllers/UserQuestionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\UserQuestion;
use App\Faq;
use LoggedAccount;

class UserQuestionController extends Controller {

    public function index($status) {
        $data = [];
        if (!in_array($status, ['new', 'reported', 'answered'])) {
            abort(404);
        }
        if (!LoggedAccount::get()->isSuperAdmin() && $status == 'reported') {
            abort(404);
        }
        $data['questions'] = UserQuestion::where('status', '=', $status)->orderBy('updated_at')->get();
        $data['partialView'] = 'user_question.list';
        $data['status'] = $status;
        return view('user_question.base', $data);
    }

    public function answer($id) {
        $question = UserQuestion::findOrFail($id);
        if ($question->status == 'answered') {
            abort(404);
        }
        $data['question'] = $question;
        $data['partialView'] = 'user_question.form';
        return view('user_question.base', $data);
    }

    public function send($id, Request $request) {
        $question = UserQuestion::findOrFail($id);
        if ($question->status == 'answered') {
            abort(404);
        }
        if (!trim($request->answer)) {
            return response()->json(['errors' => ['answer' => ['Answer must be filled']]]);
        }
        $question->answer = $request->answer;
        $question->status = 'answered';
        $question->save();
        return response()->json(['url' => route('admin.user_question.index', ['status' => 'new'])]);
    }

    public function view($id) {
        $question = UserQuestion::findOrFail($id);
        $data['question'] = $question;
        $data['partialView'] = 'user_question.view';
        return view('user_question.base', $data);
    }

    public function copy($id, Request $request) {
        $question = UserQuestion::findOrFail($id);
        if ($question->copied) {
            abort(404);
        }
        $faq = new Faq();
        $faq->question = $question->question;
        if ($question->answer) {
            $faq->answer = $question->answer;
        } else {
            $faq->answer = $request->answer;
        }
        $question->copied = true;
        $question->save();
        $faq->save();
    }

    public function report($id) {
        $question = UserQuestion::findOrFail($id);
        if ($question->status != 'new' || !LoggedAccount::get()->isCRM()) {
            abort(404);
        }
        $question->status = 'reported';
        $question->save();
        return response()->json(['url' => route('admin.user_question.index', ['status' => 'new'])]);
    }

}

resources/views/user_question/answered.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>User Questions
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                    </div>
                </div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt">
            <thead>
                <tr class="tr-head">
                    <th class="no-sorting table-checkbox-col">
                        <input type="checkbox" class="group-checkable">
                    </th>
                    <th valign="middle">
                        Question
                    </th>
                    <th class="no-sorting">
                        Actions
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach($questions as $question)
                <tr class="odd gradeX" id="data-row-{{$question->id}}">
                    <td valign="middle">
                        <input type="checkbox" name="items[]"  class="table-checkbox"  value="{{$question->id}}" >
                        <input type="hidden" value="{{$question->id}}" class="reorder-vals">
                    </td>
                    <td valign="middle">
                        {{$question->question}}
                    </td>
                    <td valign="middle">
                        <a href="{{route('admin.user_question.answer',['id'=>$question->id])}}" class="pjax-link"><button type="button" class="btn green"><i class="fa fa-edit"></i> View</button></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/user_question/base.blade.php
<?php
$i = 'faqs';
$j = 'questions';
?>

@extends('admin.master')
@section('plugins_css')
<link href="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/sweetAlert/sweetalert.css')}}"/>
@endSection

@section('plugins_js')
<script type="text/javascript" src="{{asset('assets/global/scripts/datatable.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/datatables.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/sweetAlert/sweetalert.min.js')}}"></script>

@endSection

@section('page_js')
<script type="text/javascript" src="{{asset('assets/admin/pages/scripts/user_question.js')}}"></script>
<script>
//$(document).on('ready ajax-page-loaded', function () {
//    if ($('.larajsval').length) {
//        $.getScript($('.larajsval').data('validator'));
//    }
//});
$(document).on('click', '.report', function () {
    var url = $(this).data('action');
    var $button = $(this);
    var $tr = $button.closest('tr');
    $.ajax({
        url: url,
        method: 'PATCH',
        success: function (data) {
            $button.remove();
            table.row($tr).remove().draw();
            toastr['success']('Reported successfuly', "Done");
        }
    })
});
</script>
@endSection

@section('add_inits')

@stop

@section('title')
User Questions
@stop

@section('page_title')
User Questions
@stop

@section('page_title_small')

@stop

@section('content')
@include($partialView)
@stop

resources/views/user_question/form.blade.php
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Question </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <div class="form form-horizontal" role="form" id="main-form">
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Question</label>
                    <div class="col-md-4">
                        <p>{{$question->question}}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Answer</label>
                    <div class="col-md-4">
                        <textarea name='answer' class="form-control val" rows="4">{{$question->answer or ''}}</textarea>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="btn-set pull-right">
                    @if(LoggedAccount::get()->isCRM())
                    <button type="submit" class="btn btn-lg red" id="report"
                            data-action="{{route('admin.user_question.report',['id'=>$question->id])}}"
                            data-method="patch"
                            >Pass to admin</button>
                    @endif
                    @if(!$question->copied)
                    <button type="submit" class="btn btn-lg blue" id="copy"
                            data-action="{{route('admin.user_question.copy',['id'=>$question->id])}}"
                            data-method="post"
                            >Copy to FAQs</button>
                    @endif
                    <button type="submit" class="btn btn-lg green" id="send"
                            data-action="{{route('admin.user_question.send',['id'=>$question->id])}}"
                            data-method="patch"
                            >Send</button>
                </div>
            </div>
        </div>
        <!-- END FORM-->
    </div>
</div>

resources/views/user_question/list.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>User Questions
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                        <div class="form-group">
                            <div class="md-radio-inline" id="status-filter">
                            <div class="md-radio">
                                                    <input type="radio" id="radio14" name="status" class="status-fitler" @if($status == 'new') checked @endif value="{{route('admin.user_question.index',['status'=>'new'])}}">
                                                    <label for="radio14">
                                                        <span></span>
                                                        <span class="check"></span>
                                                        <span class="box"></span> New </label>
                                                </div>
                            <div class="md-radio">
                                                    <input type="radio" id="radio142" name="status" class="status-fitler" @if($status == 'answered') checked @endif  value="{{route('admin.user_question.index',['status'=>'answered'])}}">
                                                    <label for="radio142">
                                                        <span></span>
                                                        <span class="check"></span>
                                                        <span class="box"></span> Answered </label>
                                                </div>
                            
                                                
                                
                                
                                @if(LoggedAccount::get()->isSuperAdmin())
                                <div class="md-radio">
                                                    <input type="radio" id="radio14xx" name="status" class="status-fitler" @if($status == 'reported') checked @endif  value="{{route('admin.user_question.index',['status'=>'reported'])}}">
                                                    <label for="radio14xx">
                                                        <span></span>
                                                        <span class="check"></span>
                                                        <span class="box"></span> Reported </label>
                                                </div>
                               
                                @endif
                            </div>
                            
                            
                        </div>                    
                    </div>
                </div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt">
            <thead>
                <tr class="tr-head">
                    <th class="no-sorting table-checkbox-col">
                        <input type="checkbox" class="group-checkable">
                    </th>
                    <th valign="middle">
                        Question
                    </th>
                    <th class="no-sorting">
                        Actions
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach($questions as $question)
                <tr class="odd gradeX" id="data-row-{{$question->id}}">
                    <td valign="middle">
                        <input type="checkbox" name="items[]"  class="table-checkbox"  value="{{$question->id}}" >
                        <input type="hidden" value="{{$question->id}}" class="reorder-vals">
                    </td>
                    <td valign="middle">
                        {{$question->question}}
                    </td>
                    <td valign="middle">
                        @if($status == 'answered')
                        <a href="{{route('admin.user_question.view',['id'=>$question->id])}}" class="pjax-link"><button type="button" class="btn yellow"><i class="fa fa-edit"></i> View</button></a>
                        @else
                        <a href="{{route('admin.user_question.answer',['id'=>$question->id])}}" class="pjax-link"><button type="button" class="btn green"><i class="fa fa-edit"></i> Answer</button></a>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/user_question/view.blade.php
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Question </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <div class="form form-horizontal" role="form" id="main-form">
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Question</label>
                    <div class="col-md-4">
                        <p>{{$question->question}}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Answer</label>
                    <div class="col-md-4">
                        <p>{{$question->answer}}</p>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="btn-set pull-right">
                    @if(!$question->copied)
                    <button type="submit" class="btn btn-lg blue" id="copy"
                            data-action="{{route('admin.user_question.copy',['id'=>$question->id])}}"
                            data-method="patch"
                            >Copy to FAQs</button>
                    @endif
                </div>
            </div>
        </div>
        <!-- END FORM-->
    </div>
</div>