app/Http/routes.php
    Route::get('level/{id}/material', 'OneOnOneController@material')->name('material');
    Route::delete('level/{id}/delete_material', 'OneOnOneController@deleteMaterial')->name('delete_material');
    Route::post('{id}/upload_section_image', 'OneOnOneController@uploadSectionImage')->name('upload_section_image');
    Route::get('level/{id}/section_image', 'OneOnOneController@sectionImage')->name('section_image');
    Route::delete('level/{id}/delete_section_image', 'OneOnOneController@deleteSectionImage')->name('delete_section_image');
    Route::post('{id}upload_course_image', 'OneOnOneController@uploadCourseImage')->name('upload_course_image');
    Route::get('level/{id}/course_image', 'OneOnOneController@courseImage')->name('course_image');
    Route::delete('level/{id}/delete_course_image', 'OneOnOneController@deleteCourseImage')->name('delete_course_image');
    Route::post('{id}/upload_promo', 'OneOnOneController@uploadPromo')->name('upload_promo');
    Route::get('level/{id}/promo', 'OneOnOneController@promo')->name('promo');
    Route::delete('level/{id}/delete_promo', 'OneOnOneController@deletePromo')->name('delete_promo');
    Route::get('{id}/edit', 'OneOnOneController@edit')->name('edit');
    Route::patch('{id}/update', 'OneOnOneController@update')->name('update');
    Route::patch('{id}/publish', 'OneOnOneController@publish')->name('publish');
});

Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/blended", 'as' => "admin.blended."], function () {
    Route::get('/', 'BlendedController@index')->name('index');
    Route::post('init', 'BlendedController@init')->name('init');
    Route::get('{id}/edit', 'BlendedController@edit')->name('edit');
    Route::delete('{id}/delete', 'BlendedController@delete')->name('delete');
    Route::post('{id}/upload_section_image', 'BlendedController@uploadSectionImage')->name('upload_section_image');
    Route::post('{id}/upload_course_image', 'BlendedController@uploadCourseImage')->name('upload_course_image');
    Route::post('{id}/upload_course_material', 'BlendedController@uploadCourseMaterial')->name('upload_course_material');
    Route::post('{id}/upload_promo', 'BlendedController@uploadPromo')->name('upload_promo');
    Route::get('{id}/section_image', 'BlendedController@sectionImage')->name('section_image');
    Route::get('{id}/course_image', 'BlendedController@courseImage')->name('course_image');
    Route::get('{id}/course_material', 'BlendedController@courseMaterial')->name('course_material');
    Route::get('{id}/promo', 'BlendedController@promo')->name('promo');
    Route::delete('{id}/delete_section_image', 'BlendedController@deleteSectionImage')->name('delete_section_image');
    Route::delete('{id}/delete_course_image', 'BlendedController@deleteCourseImage')->name('delete_course_image');
    Route::delete('{id}/delete_course_material', 'BlendedController@deleteCourseMaterial')->name('delete_course_material');
    Route::delete('{id}/delete_promo', 'BlendedController@deletePromo')->name('delete_promo');
    Route::patch('{id}/update', 'BlendedController@update')->name('update');
    Route::patch('{id}/publish', 'BlendedController@publish')->name('publish');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/blended_template", 'as' => "admin.blended_template."], function () {
    Route::get('/', 'BlendedTemplateController@index')->name('index');
    Route::post('init', 'BlendedTemplateController@init')->name('init');
    Route::get('{id}/edit', 'BlendedTemplateController@edit')->name('edit');
    Route::post('{id}/upload_ig', 'BlendedTemplateController@uploadIg')->name('upload_ig');
    Route::get('{id}/ig', 'BlendedTemplateController@ig')->name('ig');
    Route::delete('{id}/delete_ig', 'BlendedTemplateController@deleteIg')->name('delete_ig');
    Route::patch('{id}/update', 'BlendedTemplateController@update')->name('update');
    Route::patch('{id}/publish', 'BlendedTemplateController@publish')->name('publish');
    Route::post('{id}/init_session', 'BlendedTemplateController@initSession')->name('init_session');
    Route::delete('{id}/delete_session', 'BlendedTemplateController@deleteSession')->name('delete_session');
    Route::post('{id}/upload_session_material', 'BlendedTemplateController@uploadSessionMaterial')->name('upload_session_material');
    Route::get('{id}/session_material', 'BlendedTemplateController@session_material')->name('session_material');
    Route::delete('{id}/delete_session_material', 'BlendedTemplateController@deleteSessionMaterial')->name('delete_session_material');
    Route::post('{id}/upload_session_content', 'BlendedTemplateController@uploadSessionContent')->name('upload_session_content');
    Route::get('{id}/session_content', 'BlendedTemplateController@session_content')->name('session_content');
    Route::delete('{id}/delete_session_content', 'BlendedTemplateController@deleteSessionContent')->name('delete_session_content');
    Route::delete('{id}/delete', 'BlendedTemplateController@delete')->name('delete');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/blended_schedule", 'as' => "admin.blended_schedule."], function () {
    Route::get('/', 'BlendedScheduleController@index')->name('index');
    Route::post('init', 'BlendedScheduleController@init')->name('init');
    Route::get('{id}/edit', 'BlendedScheduleController@edit')->name('edit');
    Route::delete('{id}/delete', 'BlendedScheduleController@delete')->name('delete');
    Route::patch('{id}/update', 'BlendedScheduleController@update')->name('update');
    Route::patch('{id}/publish', 'BlendedScheduleController@publish')->name('publish');
    Route::get('{id}/students', 'BlendedScheduleController@students')->name('students');
    Route::post('{id}/add_student', 'BlendedScheduleController@addStudent')->name('add_student');
    Route::delete('{id}/delete_student', 'BlendedScheduleController@deleteStudent')->name('delete_student');
    Route::get('templates', 'BlendedScheduleController@templates')->name('templates');
    Route::get('sessions', 'BlendedScheduleController@sessions')->name('sessions');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/one_schedule", 'as' => "admin.one_schedule."], function () {
    Route::get('/', 'OneScheduleController@index')->name('index');
    Route::post('init', 'OneScheduleController@init')->name('init');
    Route::get('{id}/edit', 'OneScheduleController@edit')->name('edit');
    Route::delete('{id}/delete', 'OneScheduleController@delete')->name('delete');
    Route::get('students', 'OneScheduleController@students')->name('students');
    Route::get('teachers', 'OneScheduleController@teachers')->name('teachers');
    Route::patch('{id}/update', 'OneScheduleController@update')->name('update');
    Route::patch('{id}/publish', 'OneScheduleController@publish')->name('publish');
    Route::delete('{id}/delete', 'OneScheduleController@delete')->name('delete');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/elearning", 'as' => "admin.elearning.", 'namespace' => 'Elearning'], function () {
    Route::group(['prefix' => 'course', 'as' => 'course.'], function () {
        Route::get('/', 'CourseController@index')->name('index');
        Route::post('init', 'CourseController@init')->name('init');
        Route::get('{id}/edit', 'CourseController@edit')->name('edit');
        Route::patch('{id}/update', 'CourseController@update')->name('update');
        Route::patch('{id}/publish', 'CourseController@publish')->name('publish');
    });
    Route::group(['prefix' => 'module', 'as' => 'module.'], function () {
        Route::post('{course_id}/init', 'ModuleController@init')->name('init');
        Route::delete('{id}/delete', 'ModuleController@delete')->name('delete');
        Route::post('{id}/upload_content', 'ModuleController@uploadContent')->name('upload_content');
        Route::post('{id}/upload_material', 'ModuleController@uploadMaterial')->name('upload_material');
        Route::delete('{id}/delete_content', 'ModuleController@deleteContent')->name('delete_content');
        Route::delete('{id}/delete_material', 'ModuleController@deleteMaterial')->name('delete_material');
    });
    Route::group(['prefix' => 'lesson', 'as' => 'lesson.'], function () {
        Route::post('{course_id}/init', 'LessonController@init')->name('init');
        Route::delete('{id}/delete', 'LessonController@delete')->name('delete');
        Route::post('{id}/upload_content', 'LessonController@uploadContent')->name('upload_content');
        Route::post('{id}/upload_material', 'LessonController@uploadMaterial')->name('upload_material');
        Route::delete('{id}/delete_content', 'LessonController@deleteContent')->name('delete_content');
        Route::delete('{id}/delete_material', 'LessonController@deleteMaterial')->name('delete_material');
    });
    Route::group(['prefix' => 'topic', 'as' => 'topic.'], function () {
        Route::post('{course_id}/init', 'TopicController@init')->name('init');
        Route::delete('{id}/delete', 'TopicController@delete')->name('delete');
        Route::post('{id}/upload_content', 'TopicController@uploadContent')->name('upload_content');
        Route::post('{id}/upload_material', 'TopicController@uploadMaterial')->name('upload_material');
        Route::delete('{id}/delete_content', 'TopicController@deleteContent')->name('delete_content');
        Route::delete('{id}/delete_material', 'TopicController@deleteMaterial')->name('delete_material');
    });
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/quizzes", 'as' => "admin.quizzes."], function () {
    Route::get('/', 'quizController@index')->name('index');
    Route::post('init', 'quizController@init')->name('init');
    Route::get('{id}/edit', 'quizController@edit')->name('edit');
    Route::post('question_add/{quiz_id}', 'quizController@addQuestion')->name('question_add');

app/BlendedTemplate.php
<?php

namespace App;

use App\File;
use Illuminate\Database\Eloquent\Model;

class BlendedTemplate extends Model {

    use Traits\TrimScalarValues;

    private $ig = null;

    public static function boot() {
        parent::boot();
        static::deleting(function ($template) {
            $template->deleteIg();
            $template->sessions()->delete();
        });
    }

    public function course() {
        return $this->belongsTo('App\BlendedCourse', 'course_id');
    }

    public function schedules() {
        return $this->hasMany('App\BlendedSchedule', 'template_id');
    }

    public function sessions() {
        return $this->hasMany('App\BlendedSession', 'template_id');
    }

    public function ig() {
        if (is_null($this->ig_id)) {
            return null;
        }
        if (is_null($this->ig)) {
            $this->ig = File::find($this->ig_id);
            return $this->ig;
        }
        return $this->ig;
    }

    public function deleteIg() {
        if ($this->ig()) {
            $this->ig()->delete();
            $this->ig_id = null;
            $this->save();
        }
    }

}

resources/views/blended_template/base.blade.php
<?php $i = 'blended'; $j='templates';?>
@extends('admin.master')
@section('plugins_css')
<link href="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/sweetAlert/sweetalert.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/dragula/dragula.min.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/jquery-nestable/jquery.nestable.css')}}"/>
<style>
    .bordered{
        margin-bottom: 5px;
        border-style: solid;
        border-width: 3px;
        padding: 30px;
        border-color: black;
    }
    .handle-hidden{
        visibility: hidden;
        height: 0;
        margin:0;
        padding:0;
    }
</style>
@endSection

@section('plugins_js')
<script type="text/javascript" src="{{asset('assets/global/scripts/datatable.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/datatables.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/jsvalidation.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/sweetAlert/sweetalert.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/dragula/dragula.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/jquery-nestable/jquery.nestable.js')}}"></script>
@endSection

@section('page_js')
<script>
var pageAttributes = {
    indexUrl: "{{route('admin.one_on_one.index')}}",
}
</script>
<script type="text/javascript" src="{{asset('assets/ajaxForms.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/scripts.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/admin/pages/scripts/blended_template.js')}}"></script>
@endSection

@section('add_inits')

@stop

@section('title')
Blended Template
@stop

@section('page_title')
Blended Template
@stop

@section('page_title_small')

@stop

@section('content')
@include($partialView)
@stop

resources/views/blended_template/form.blade.php
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Template</div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <div  id="main-form" novalidate class="form-horizontal  form"> 
            <div class="form-body">
                <div class="mt-element-ribbon bg-grey-steel">
                    <div class="ribbon ribbon-border-hor ribbon-clip ribbon-color-primary uppercase">
                        <div class="ribbon-sub ribbon-clip"></div> Template details </div>
                    <div class="ribbon-content">
                        <div class="form-group">
                            <label>Course</label>
                            <select name="course" class="form-control val">
                                <option value="" @if(! $template->course) selected @endif></option>
                                @foreach($courses as $course)
                                <option @if($template->course && ($template->course->id == $course->id)) selected @endif value="{{$course->id}}">{{$course->title}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Title</label>
                            <input name="template_title" class="form-control val" value="{{$template->title}}">
                        </div>
                        <!-- IG -->
                        <div class="form-group">
                            <label >IG</label>
                            <input type="file" class="hidden fileinput"
                                   data-action="{{route('admin.blended_template.upload_ig',['id'=>$template->id])}}" 
                                   >
                            <div class="row">
                                <div class="col-md-8">
                                    <span class="filenameplaceholder">
                                        @if($template->ig())
                                        <a href="{{route('admin.blended_template.ig',['id'=>$template->id])}}" class="filename">
                                            {{$template->ig()->name}}
                                        </a>
                                        @else
                                        No file selected
                                        @endif
                                    </span>
                                    <div class="progress-bar progress-bar-success hidden" role="progressbar"  style="width: 0%">
                                        <span>0%</span>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <button type="button" class="btn btn-primary filepicker pull-right {{$template->ig()?'hidden':''}}">
                                        Select File
                                    </button>
                                    <button class="btn btn-danger pull-right cancel hidden">Cancel</button>
                                    <button class="btn btn-danger pull-right removefile {{$template->ig()?'':'hidden'}}" 
                                            data-action="{{route('admin.blended_template.delete_ig',['id'=>$template->id])}}"
                                            >
                                        Remove
                                    </button>
                                </div>
                            </div>
                        </div>
                        <!-- END IG -->
                        <div class="form-group">
                            <label>Number of H.Ws</label>
                            <input name="homework_count" class="form-control val" value="{{$template->homework_count}}">
                        </div>                
                    </div>
                </div>
                <!-- Sessions -->
                <div class="mt-element-ribbon bg-grey-steel">
                    <div class="ribbon ribbon-border-hor ribbon-clip ribbon-color-primary uppercase">
                        <div class="ribbon-sub ribbon-clip"></div> Sessions </div>
                    <div class="ribbon-content">
                        <div id="sessions">
                            @foreach($sessions as $session)
                            @include('blended_template.session',['session'=>$session])
                            @endforeach
                        </div>

                        <div class="form-group">
                            <button type="button" class="btn btn-primary" id="add_session" data-url="{{route('admin.blended_template.init_session',['id'=>$template->id])}}">Add a session</button>
                        </div>                
                    </div>

                </div>

                <!-- END Sessions -->
            </div>
            <div class="form-actions">
                <div class="btn-set pull-right">
                    <button type="button" class="btn btn-lg blue" id="save-all" 
                            data-action="{{route('admin.blended_template.update',['id'=>$template->id])}}">
                        Save</button>
                    <button type="button" class="btn btn-lg green" id="publish" 
                            data-action="{{route('admin.blended_template.publish',['id'=>$template->id])}}">
                        Publish</button>
                </div>
            </div>
        </div>
        <!-- END FORM-->
    </div>
</div>
<div id="hidden" class="hidden">
    @include('blended_template.session',['session'=>false])
</div>

resources/views/blended_template/list.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>Blended Templates
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                        <button class="btn green" id="add_new_template" data-action="{{route('admin.blended_template.init')}}"
                                >
                            Add New <i class="fa fa-plus"></i>
                        </button>                        
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt">
            <thead>
                <tr class="tr-head">
                    <th valign="middle">
                        Title
                    </th>
                    <th valign="middle">
                        Course
                    </th>
                    <th valign="middle">
                        Created at
                    </th>
                    <th valign="middle">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach($templates as $template)
                <tr class="odd gradeX" id="data-row-{{$template->id}}">
                    <td valign="middle">
                        {{$template->title}}
                    </td>
                    <td valign="middle">
                        @if($template->course)
                        {{$template->course->title}}
                        @endif
                    </td>
                    <td valign="middle">
                        {{$template->created_at}}
                    </td>
                    <td valign="middle">
                        <a href="{{route('admin.blended_template.edit',['id'=>$template->id])}}" class="btn green pjax-link" ><i class="fa fa-edit"></i> Edit</a> 
                        <a href="{{route('admin.blended_template.delete',['id'=>$template->id])}}" class="btn red remove-template" ><i class="fa fa-remove"></i> Delete</a> 
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/blended_template/session.blade.php
<div class="portlet box blue-hoki pricing session" data-id="{{$session?$session->id:''}}">
    <div class="portlet-title">
        <div class="caption">
            Sessions </div>
        <div class="actions tools">
            <button class="btn btn-default btn-sm remove_session" data-action="{{$session?route('admin.blended_template.delete_session',['id'=>$session->id]):''}}" type="button"><i class="fa fa-remove"></i> Remove</button>
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body">
        <div style="padding:20px;" >
            <input type="hidden" value="{{$session ? $session->id: ''}}" name="id">
            <div class="form-group">
                <label>Title</label>
                <input class="form-control" name="title" type="text" value="{{$session ? $session->title : ''}}">
            </div>
            <div class="form-group">
                <label>Duration</label>
                <input class="form-control" name="duration" type="text" value="{{$session ? $session->duration : ''}}">
            </div>
            <!--- CONTENT -->
            <div class="form-group content">
                <label >Content</label>
                <input type="file" class="hidden fileinput"
                       data-action="{{$session? route('admin.blended_template.upload_session_content',['id'=>$session->id]):''}}" 
                       >
                <div class="row">
                    <div class="col-md-8">
                        <span class="filenameplaceholder">
                            @if($session && $session->content())
                            <a href="{{route('admin.blended_template.session_content',['id'=>$session->id])}}" class="filename">
                                {{$session->content()->name}}
                            </a>
                            @else
                            No file selected
                            @endif
                        </span>
                        <div class="progress-bar progress-bar-success hidden" role="progressbar"  style="width: 0%">
                            <span>0%</span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <button type="button" class="btn btn-primary filepicker pull-right {{$session && $session->content()?'hidden':''}}">
                            Select File
                        </button>
                        <button class="btn btn-danger pull-right cancel hidden">Cancel</button>
                        <button class="btn btn-danger pull-right removefile {{$session && $session->content()?'':'hidden'}}" 
                                data-action="{{$session ? route('admin.blended_template.delete_session_content',['id'=>$session->id]):''}}"
                                >
                            Remove
                        </button>
                    </div>
                </div>
            </div>
            <!-- end CONTENT !-->
            <!-- Material -->
            <div class="form-group material">
                <label >Extra Material</label>
                <input type="file" class="hidden fileinput"
                       data-action="{{$session?route('admin.blended_template.upload_session_material',['id'=>$session->id]):''}}" 
                       >
                <div class="row">
                    <div class="col-md-8">
                        <span class="filenameplaceholder">
                            @if($session && $session->material())
                            <a href="{{route('admin.blended_template.session_material',['id'=>$session->id])}}" class="filename">
                                {{$session->material()->name}}
                            </a>
                            @else
                            No file selected
                            @endif
                        </span>
                        <div class="progress-bar progress-bar-success hidden" role="progressbar"  style="width: 0%">
                            <span>0%</span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <button type="button" class="btn btn-primary filepicker pull-right {{$session && $session->material()?'hidden':''}}">
                            Select File
                        </button>
                        <button class="btn btn-danger hidden pull-right cancel">Cancel</button>
                        <button class="btn btn-danger pull-right removefile {{$session && $session->material()?'':'hidden'}}" 
                                data-action="{{$session ? route('admin.blended_template.delete_session_material',['id'=>$session->id]): ''}}"
                                >
                            Remove
                        </button>
                    </div>
                </div>
            </div>
            <!-- end Material -->
        </div>
    </div>
</div>