app/Http/routes.php
    Route::patch('{id}/update', 'BackendUserController@update')->name('update');
    Route::delete('{id}/delete', 'BackendUserController@delete')->name('delete');
    Route::delete('delete_multiple', 'BackendUserController@deleteMultiple')->name('delete_multiple');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin/faq_category', 'as' => 'admin.faq_category.'], function() {
    Route::get('/', 'FaqCategoryController@index')->name('index');
    Route::get('create', 'FaqCategoryController@create')->name('create');
    Route::get('{id}/edit', 'FaqCategoryController@edit')->name('edit');
    Route::post('reorder', 'FaqCategoryController@reorder')->name('reorder');
    Route::post('store', 'FaqCategoryController@store')->name('store');
    Route::patch('{id}/update', 'FaqCategoryController@update')->name('update');
    Route::delete('{id}/delete', 'FaqCategoryController@delete')->name('delete');
    Route::delete('delete_multiple', 'FaqCategoryController@deleteMultiple')->name('delete_multiple');
});
Route::group(['middleware' => ['auth', 'faqs'], 'prefix' => "admin/faq", 'as' => "admin.faq."], function () {
    Route::get('create', 'FaqController@create')->name('create');
    Route::get('{status}', 'FaqController@index')->name('index');
    Route::get('{id}/edit', 'FaqController@edit')->name('edit');
    Route::get('{id}/review_pending', 'FaqController@reviewPending')->name('review_pending');
    Route::delete('{id}/delete', 'FaqController@delete')->name('delete');
    Route::delete('delete_multiple', 'FaqController@deleteMultiple')->name('delete_multiple');
    Route::post('{id}/reorder', 'FaqController@reorder')->name('reorder');
    Route::post('store', 'FaqController@store')->name('store');
    Route::patch('{id}/update', 'FaqController@update')->name('update');
    Route::post('publish_new', 'FaqController@publishNew')->name('publish_new');
    Route::patch('{id}/publish', 'FaqController@publish')->name('publish');
    Route::get('{id}/modify', 'FaqController@getModify')->name('get_modify');
    Route::get('{id}/review_modification', 'FaqController@reviewModification')->name('review_modification');
    Route::patch('{id}/modify', 'FaqController@modify')->name('modify');
    Route::delete('{id}/reject', 'FaqController@reject')->name('reject');
    Route::patch('{id}/confirm', 'FaqController@confirm')->name('confirm');
    Route::patch('{id}/confirm_modification', 'FaqController@confirmModification')->name('confirm_modification');
    Route::delete('{id}/reject_modification', 'FaqController@rejectModification')->name('reject_modification');
});
Route::group(['middleware' => ['auth', 'faqs'], 'prefix' => "admin/user_question", 'as' => "admin.user_question."], function () {
    Route::get('{status}', 'UserQuestionController@index')->name('index');
    Route::get('{id}/answer', 'UserQuestionController@answer')->name('answer');
    Route::get('{id}/view', 'UserQuestionController@view')->name('view');
    Route::patch('{id}/send', 'UserQuestionController@send')->name('send');
    Route::post('{id}/copy', 'UserQuestionController@copy')->name('copy');
    Route::patch('{id}/report', 'UserQuestionController@report')->name('report');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/one_on_one", 'as' => "admin.one_on_one."], function () {
    Route::get('/', 'OneOnOneController@index')->name('index');
    Route::post('init', 'OneOnOneController@init')->name('init');
    Route::post('{id}/init_level', 'OneOnOneController@initLevel')->name('init_level');
    Route::delete('{id}/delete', 'OneOnOneController@delete')->name('delete');
    Route::delete('{id}/delete_level', 'OneOnOneController@deleteLevel')->name('delete_level');
    Route::post('{id}/init_objective', 'OneOnOneController@initObjective')->name('init_objective');
    Route::delete('delete_objective', 'OneOnOneController@deleteObjective')->name('delete_objective');
    Route::post('{id}/init_pricing', 'OneOnOneController@initPricing')->name('init_pricing');
    Route::delete('{id}delete_pricing', 'OneOnOneController@deletePricing')->name('delete_pricing');
    Route::patch('{id}/update', 'OneOnOneController@store')->name('update');
    Route::patch('{id}/publish', 'OneOnOneController@publish')->name('publish');
    Route::post('{id}/upload_ig', 'OneOnOneController@uploadIg')->name('upload_ig');
    Route::get('level/{id}/ig', 'OneOnOneController@ig')->name('ig');
    Route::delete('level/{id}/delete_ig', 'OneOnOneController@deleteIg')->name('delete_ig');
    Route::post('{id}/upload_material', 'OneOnOneController@uploadMaterial')->name('upload_material');
    Route::get('level/{id}/material', 'OneOnOneController@material')->name('material');
    Route::delete('level/{id}/delete_material', 'OneOnOneController@deleteMaterial')->name('delete_material');
    Route::post('{id}/upload_section_image', 'OneOnOneController@uploadSectionImage')->name('upload_section_image');
    Route::get('level/{id}/section_image', 'OneOnOneController@sectionImage')->name('section_image');
    Route::delete('level/{id}/delete_section_image', 'OneOnOneController@deleteSectionImage')->name('delete_section_image');
    Route::post('{id}upload_course_image', 'OneOnOneController@uploadCourseImage')->name('upload_course_image');
    Route::get('level/{id}/course_image', 'OneOnOneController@courseImage')->name('course_image');
    Route::delete('level/{id}/delete_course_image', 'OneOnOneController@deleteCourseImage')->name('delete_course_image');
    Route::post('{id}/upload_promo', 'OneOnOneController@uploadPromo')->name('upload_promo');
    Route::get('level/{id}/promo', 'OneOnOneController@promo')->name('promo');
    Route::delete('level/{id}/delete_promo', 'OneOnOneController@deletePromo')->name('delete_promo');
    Route::get('{id}/edit', 'OneOnOneController@edit')->name('edit');
    Route::patch('{id}/update', 'OneOnOneController@update')->name('update');
    Route::patch('{id}/publish', 'OneOnOneController@publish')->name('publish');
});

Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/blended", 'as' => "admin.blended."], function () {
    Route::get('/', 'BlendedController@index')->name('index');
    Route::post('init', 'BlendedController@init')->name('init');
    Route::get('{id}/edit', 'BlendedController@edit')->name('edit');
    Route::delete('{id}/delete', 'BlendedController@delete')->name('delete');
    Route::post('{id}/upload_section_image', 'BlendedController@uploadSectionImage')->name('upload_section_image');
    Route::post('{id}/upload_course_image', 'BlendedController@uploadCourseImage')->name('upload_course_image');
    Route::post('{id}/upload_course_material', 'BlendedController@uploadCourseMaterial')->name('upload_course_material');
    Route::post('{id}/upload_promo', 'BlendedController@uploadPromo')->name('upload_promo');
    Route::get('{id}/section_image', 'BlendedController@sectionImage')->name('section_image');
    Route::get('{id}/course_image', 'BlendedController@courseImage')->name('course_image');
    Route::get('{id}/course_material', 'BlendedController@courseMaterial')->name('course_material');
    Route::get('{id}/promo', 'BlendedController@promo')->name('promo');
    Route::delete('{id}/delete_section_image', 'BlendedController@deleteSectionImage')->name('delete_section_image');
    Route::delete('{id}/delete_course_image', 'BlendedController@deleteCourseImage')->name('delete_course_image');
    Route::delete('{id}/delete_course_material', 'BlendedController@deleteCourseMaterial')->name('delete_course_material');
    Route::delete('{id}/delete_promo', 'BlendedController@deletePromo')->name('delete_promo');
    Route::patch('{id}/update', 'BlendedController@update')->name('update');
    Route::patch('{id}/publish', 'BlendedController@publish')->name('publish');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/blended_template", 'as' => "admin.blended_template."], function () {
    Route::get('/', 'BlendedTemplateController@index')->name('index');
    Route::post('init', 'BlendedTemplateController@init')->name('init');
    Route::get('{id}/edit', 'BlendedTemplateController@edit')->name('edit');
    Route::post('{id}/upload_ig', 'BlendedTemplateController@uploadIg')->name('upload_ig');
    Route::get('{id}/ig', 'BlendedTemplateController@ig')->name('ig');
    Route::delete('{id}/delete_ig', 'BlendedTemplateController@deleteIg')->name('delete_ig');
    Route::patch('{id}/update', 'BlendedTemplateController@update')->name('update');
    Route::patch('{id}/publish', 'BlendedTemplateController@publish')->name('publish');
    Route::post('{id}/init_session', 'BlendedTemplateController@initSession')->name('init_session');
    Route::delete('{id}/delete_session', 'BlendedTemplateController@deleteSession')->name('delete_session');
    Route::post('{id}/upload_session_material', 'BlendedTemplateController@uploadSessionMaterial')->name('upload_session_material');
    Route::get('{id}/session_material', 'BlendedTemplateController@session_material')->name('session_material');
    Route::delete('{id}/delete_session_material', 'BlendedTemplateController@deleteSessionMaterial')->name('delete_session_material');
    Route::post('{id}/upload_session_content', 'BlendedTemplateController@uploadSessionContent')->name('upload_session_content');
    Route::get('{id}/session_content', 'BlendedTemplateController@session_content')->name('session_content');
    Route::delete('{id}/delete_session_content', 'BlendedTemplateController@deleteSessionContent')->name('delete_session_content');
    Route::delete('{id}/delete', 'BlendedTemplateController@delete')->name('delete');
});
Route::group(['middleware' => ['auth', 'admin'], 'prefix' => "admin/blended_schedule", 'as' => "admin.blended_schedule."], function () {
    Route::get('/', 'BlendedScheduleController@index')->name('index');
    Route::post('init', 'BlendedScheduleController@init')->name('init');

resources/views/one_on_one/hidden/level.blade.php
<div class="portlet box blue-hoki level" data-id="{{$level?$level->id:''}}">
    <div class="portlet-title">
        <div class="caption">
            {{$level ? $level->title: ''}} </div>
        <div class="actions tools">
            <button class="btn btn-default btn-sm remove_level"
                    data-action="{{$level?route('admin.one_on_one.delete_level',['id'=>$level->id]):''}}"
                    type="button"><i class="fa fa-remove"></i> Remove</button>
            <a href="javascript:;" class="expand"> </a>
        </div>
    </div>
    <div class="portlet-body display-hide">
        <input type="hidden" value="{{$level ? $level->id: ''}}" name="id">
        <div class="form-group">
            <label>Title</label>
            <input class="form-control" name="title" type="text" value="{{$level?$level->title:''}}">
        </div>
        <!--- IG -->
        <div class="form-group ig">
            <label >IG</label>
            <input type="file" class="hidden fileinput"
                   data-action="{{$level?route('admin.one_on_one.upload_ig',['id'=>$level->id]):''}}" 
                   data-delete="{{$level?route('admin.one_on_one.delete_ig',['id'=>$level->id]):''}}"
                   >
            <div class="row">
                <div class="col-md-8">
                    <span class="filenameplaceholder">
                        @if($level && $level->ig())
                        <a href="{{route('admin.one_on_one.ig',['id'=>$level->id])}}" class="filename">
                            {{$level->ig()->name}}
                        </a>
                        @else
                        No file selected
                        @endif
                    </span>
                    <div class="progress-bar progress-bar-success hidden" role="progressbar"  style="width: 0%">
                        <span>0%</span>
                    </div>
                </div>
                <div class="col-md-4">
                    <button type="button" class="btn btn-primary filepicker pull-right {{$level && $level->ig()?'hidden':''}}">
                        Select File
                    </button>
                    <button class="btn btn-danger pull-right cancel hidden">Cancel</button>
                    <button class="btn btn-danger pull-right removefile {{$level && $level->ig()?'':'hidden'}}" 
                            data-action="{{$level?route('admin.one_on_one.delete_ig',['id'=>$level->id]):''}}"
                            >
                        Remove
                    </button>
                </div>
            </div>
        </div>
        <!-- end IG !-->
        <!-- Material -->
        <div class="form-group material">
            <label >Material</label>
            <input type="file" class="hidden fileinput"
                   data-action="{{$level?route('admin.one_on_one.upload_material',['id'=>$level->id]):''}}" 
                   data-delete="{{$level?route('admin.one_on_one.delete_material',['id'=>$level->id]):''}}"
                   >
            <div class="row">
                <div class="col-md-8">
                    <span class="filenameplaceholder">
                        @if($level && $level->material())
                        <a href="{{route('admin.one_on_one.ig',['id'=>$level->id])}}" class="filename">
                            {{$level->material()->name}}
                        </a>
                        @else
                        No file selected
                        @endif
                    </span>
                    <div class="progress-bar progress-bar-success hidden" role="progressbar"  style="width: 0%">
                        <span>0%</span>
                    </div>
                </div>
                <div class="col-md-4">
                    <button type="button" class="btn btn-primary filepicker pull-right {{$level && $level->material()?'hidden':''}}">
                        Select File
                    </button>
                    <button class="btn btn-danger hidden pull-right cancel">Cancel</button>
                    <button class="btn btn-danger pull-right removefile {{$level && $level->material()?'':'hidden'}}" 
                            data-action="{{$level?route('admin.one_on_one.delete_material',['id'=>$level->id]):''}}"
                            >
                        Remove
                    </button>
                </div>
            </div>
        </div>
        <!-- end Material -->


    </div>
</div>

resources/views/one_on_one/hidden/pricing.blade.php
<div class="portlet box blue-hoki pricing" data-id="{{$pricing?$pricing->id:''}}">
    <div class="portlet-title">
        <div class="caption">
            {{$pricing ? $pricing->count : ''}} Sessions </div>
        <div class="actions tools">
            <button class="btn btn-default btn-sm remove_pricing"
                    data-action="{{$pricing?route('admin.one_on_one.delete_pricing',['id'=>$pricing->id]):''}}"
                    type="button"><i class="fa fa-remove"></i> Remove</button>
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="form-inline">
            <input type="hidden"  name="id" value="{{$pricing? $pricing->id : ''}}">
            <div class="form-group">
                <input type="text" name="count" class="form-control" placeholder="Count" value="{{$pricing? $pricing->count: ''}}">
            </div>
            <div class="form-group">
                <input type="text" name="basic_basic" class="form-control" placeholder="B Teacher-B Time" value="{{$pricing ? $pricing->basic_basic: ''}}">
            </div>
            <div class="form-group">
                <input type="text" name="basic_premium" class="form-control" placeholder="B Teacher-P Time" value="{{$pricing? $pricing->basic_premium: ''}}">
            </div>
            <div class="form-group">
                <input type="text" name="premium_basic" class="form-control" placeholder="P Teacher-B Time" value="{{$pricing? $pricing->premium_basic:''}}">
            </div>
            <div class="form-group">
                <input type="text" name="premium_premium" class="form-control" placeholder="P Teacher-P Time" value="{{$pricing? $pricing->premium_premium:''}}">
            </div>
        </div>
    </div>
</div>